---
- name: Retrieve k3s.yml
  hosts: all
  gather_facts: no
  tasks:

  - name: Fetch k3s.yml
    fetch:
      src: /etc/rancher/k3s/k3s.yaml
      dest: ~/.kube/config
      mode: 0600
      flat: yes
    become: yes
    when: inventory_hostname == groups['masters'][0]