- name: Install k3s on bramble of Raspberry Pis
  hosts: all
  become: true
  vars_files:
    - vars/main.yml
    - vars/vault

  roles:
    - role: common
      tags: common

    - role: log2ram
      vars:
        - log_folder_size: '{{ log2ram.folder_size }}'
      tags: log2ram
    
    - role: keepalived-vip
      vars:
        - vip_pass: '{{ vip.pass }}'
        - vip_ip: '{{ vip.ip }}'
      when: vip_priority is defined
      tags: vip

    - role: k3s-install
      vars:
        - k3s_token: '{{ k3s.token }}'
        - k3s_channel: "{{ k3s.channel }}"