- name: Install k3s on bramble of Raspberry Pis
  hosts: all
  become: true
  vars_files:
    - vars/main.yaml
    - vars/vault

  roles:
    - role: common
      tags: common

    - role: automount-luks
      tags: luks
      when: drives is defined

    - role: log2ram
      vars:
        - log_folder_size: '{{ log2ram.folder_size }}'
      tags: log2ram

    - role: k3s-install
      vars:
        - k3s_token: '{{ k3s.token }}'
        - k3s_channel: "{{ k3s.channel }}"
        - k3s_vip: '{{ vip }}'
