---
# tasks file for roles/keepalived-vip
- name: Check if VIP defined
  fail:
    msg: Must define a VIP
  when: vip_ip is undefined

- name: Install keepalived
  package:
    name: keepalived
    state: present
  when: vip_priority is defined

- name: Apply keepalived.conf
  template:
    src: templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart keepalived

- name: Start keepalived
  service:
    name: keepalived
    enabled: true
    state: started
