---
- name: Enable cgroup via boot commandline if not already enabled for Ubuntu 20.04
  lineinfile:
    path: /boot/firmware/cmdline.txt
    backrefs: yes
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
  register: cgroup_result

- name: Reboot host to enable cgroups
  reboot:
  when: cgroup_result.changed