---
# tasks file for k3s-install
- name: Check for k3s token
  fail:
    msg: Must provide a token for k3s
  when: k3s_token is undefined

- name: Get k3s install script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s.sh
    mode: '755'

- name: Install k3s on first master
  command: 
    argv:
    - /tmp/k3s.sh 
    - server
    - --cluster-init
  environment:
    K3S_TOKEN: '{{ k3s_token }}'
  when: ansible_host in groups['masters'][0]

- name: Install k3s on masters
  command: 
    argv:
    - /tmp/k3s.sh 
    - server 
    - --server https://{{ groups['masters'][0] }}:6443
  environment:
    K3S_TOKEN: '{{ k3s_token }}'
  when: ansible_host in groups['masters'][1:]

- name: Install k3s on workers
  command:
    argv:
    - /tmp/k3s.sh 
    - agent 
    - --server https://{{ groups['masters'][0] }}:6443
  environment:
    K3S_TOKEN: '{{ k3s_token }}'
  when: ansible_host in groups['workers']