---
# tasks file for k3s-install
- name: Check for k3s token
  fail:
    msg: Must provide a token for k3s
  when: k3s_token is undefined

- name: Enable cgroups on Ubuntu 18.04
  include_tasks: cgroups_ubuntu18.yml
  when: 
    - ansible_distribution_major_version == "18"
    - ansible_facts['distribution'] == 'Ubuntu'

- name: Enable cgroups on Ubuntu 20.04
  include_tasks: cgroups_ubuntu20.yml
  when: 
    - ansible_distribution_major_version == "20"
    - ansible_facts['distribution'] == 'Ubuntu'

- name: Enable cgroups on Pi OS
  include_tasks: cgroups_pi_os.yml
  when: ansible_facts['distribution'] == 'Debian'

- name: Ensure Rancher manifests directory exists
  file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: inventory_hostname in groups['masters']

- name: Add kube-vip manifest
  template:
    src: vip.yaml
    dest: /var/lib/rancher/k3s/server/manifests/vip.yaml
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname in groups['masters']

- name: Get k3s install script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s.sh
    mode: '755'

- name: Install k3s on first master
  command: 
    argv:
    - /tmp/k3s.sh 
    - server
    - --cluster-init
    - --disable
    - local-storage
    - --tls-san
    - "{{ k3s_vip }}"
  environment:
    K3S_TOKEN: '{{ k3s_token }}'
    INSTALL_K3S_CHANNEL: '{{ k3s_channel }}'
    K3S_KUBECONFIG_MODE: 644
  when: inventory_hostname == groups['masters'][0]
  args:
    creates: /var/lib/rancher/k3s/server/node-token
  register: master_deploy

- name: Pause for 5 minutes to allow initial master to fully deploy
  pause:
    minutes: 5
  when: master_deploy.changed
  delegate_to: localhost

- name: Install k3s on masters
  command: 
    argv:
    - /tmp/k3s.sh 
    - server 
    - --server
    - https://{{ groups['masters'][0] }}:6443
    - --disable
    - local-storage
    - --tls-san
    - "{{ k3s_vip }}"
  environment:
    K3S_TOKEN: '{{ k3s_token }}'
    INSTALL_K3S_CHANNEL: '{{ k3s_channel }}'
    K3S_KUBECONFIG_MODE: 644
  when: inventory_hostname in groups['masters'][1:]
  args:
    creates: /var/lib/rancher/k3s/server/node-token
  ignore_errors: yes

- name: Ensure k3s is started
  service:
    name: k3s
    state: started
    enabled: yes
  when: inventory_hostname in groups['masters']

- name: Install k3s on workers
  command:
    argv:
    - /tmp/k3s.sh 
    - agent 
    - --server
    - https://{{ groups['masters'][0] }}:6443
  environment:
    K3S_TOKEN: '{{ k3s_token }}'
    INSTALL_K3S_CHANNEL: '{{ k3s_channel }}'
  when: inventory_hostname in groups['workers']
  args:
    creates: /var/lib/rancher/k3s/agent/client-ca.crt

- name: Change k3s.yaml to use VIP
  replace:
    path: /etc/rancher/k3s/k3s.yaml
    regexp: "server: https://127.0.0.1:6443"
    replace: "server: https://{{ k3s_vip }}:6443"
  when: inventory_hostname in groups['masters']
