---
- name: Include Debian updates
  include_tasks: setup-deb.yml
  when: ansible_distribution_file_variety == "Debian"

- name: Change current runlevel
  command: systemctl isolate multi-user.target

- name: Change runlevel default target
  command: systemctl set-default multi-user.target

- name: Change hostname
  hostname:
    name: '{{ inventory_hostname }}'

- name: Create /etc/hosts
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root

- name: Move /tmp to tmpfs
  mount:
    path: /tmp
    src: tmpfs
    fstype: tmpfs
    opts: rw,nodev,nosuid
    state: mounted