---
- name: Update all packages
  apt:
    name: '*'
    state: latest
    update_cache: yes
    autoremove: yes

- name: Install prereqs
  apt:
    name: '{{ item }}'
    state: latest
  loop:
  - f2fs-tools
  - nfs-common
  - cryptsetup
  
- name: Remove unnecessary packages
  apt:
    name: '{{ item }}'
    state: absent
    autoremove: yes
  loop:
  - snapd

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_flag

- name: Reboot hosts if required
  reboot:
  when: reboot_flag.stat.exists