---
- name: Update all packages
  apt:
    name: '*'
    state: latest
    update_cache: yes
    autoremove: yes

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_flag

- name: Reboot hosts if required
  reboot:
  when: reboot_flag.stat.exists